### ISSUE TITLE
"we want no change", stays on the screen.

### ISSUE THREAD

**Issue by viktorstrate** [guillaume-alvarez/ShapeOfThingsThatWere#35]
If you click on a city, and you press "we want no change", and then click away again. The little popup wonn't go away before you press it.

**Comment by guillaume-alvarez** [comment]
Thanks for the report, it should be corrected by now. :+1: 

Do not hesitate to provide more feedback!

**Comment by viktorstrate** [comment]
I'm glad you could use it :)
